### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by MarkTreeSMS** [PaulMakesStuff/Python_Cross_Stitch#1]
Hello. Apologies as I am very new to programming if my issue is not what I think. I have tried running your code but believe i have a problem with some referenced files such as "dmc_dict.csv" not bring available in the files section? Are they found elsewhere? I am very excited if I could get your code working to make a custom cross stitch for my wife. Thanks

**Comment by PaulMakesStuff** [comment]
Sorry, completely missed this - it is now there!
